; ============================================================
; UAV Obstacle Path Mapping
; ============================================================

[platformio]
default_envs = teensy40

; ============================================================
; Embedded Teensy 4.0 Deployment
; ============================================================
[env:teensy40]
platform = teensy
board = teensy40
framework = arduino

lib_deps =
    bblanchon/ArduinoJson

build_flags =
    -O3
    -std=c++17
    -mfloat-abi=hard
    -mfpu=fpv5-d16

; ============================================================
; Desktop / Host Unit Testing
; ============================================================
[env:native]
platform = native
build_type = release

lib_deps =
    bblanchon/ArduinoJson

build_flags =
    -O3
    -std=c++17